"""Init users_table

Revision ID: 74cdf8275a31
Revises: a8715fa22ce5
Create Date: 2026-02-28 11:46:54.043766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '74cdf8275a31'
down_revision: Union[str, Sequence[str], None] = 'a8715fa22ce5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=False))
    op.add_column('users', sa.Column('jabatan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('face_registered', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('users', 'face_encoding',
               existing_type=postgresql.BYTEA(),
               type_=postgresql.ARRAY(sa.Float()),
               existing_nullable=True)
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('users', 'face_encoding',
               existing_type=postgresql.ARRAY(sa.Float()),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'face_registered')
    op.drop_column('users', 'jabatan')
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
